services:
  postgres:
    image: postgres:17-alpine
    container_name: auth-service-database-postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    networks:
      - task-planner-network
    environment:
       POSTGRES_USER: ${POSTGRES_USER}
       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
       POSTGRES_DB: auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka_kraft
    volumes:
      - kafka-data:/var/lib/kafka/data
#    ports:
#      - "9092:9092"
    networks:
      - task-planner-network
    environment:
      - KAFKA_NODE_ID=${KAFKA_NODE_ID}
      - KAFKA_PROCESS_ROLES=${KAFKA_PROCESS_ROLES}
      - KAFKA_CONTROLLER_QUORUM_VOTERS=${KAFKA_CONTROLLER_QUORUM_VOTERS}

      - KAFKA_LISTENERS=${KAFKA_LISTENERS}
      - KAFKA_INTER_BROKER_LISTENER_NAME=${KAFKA_INTER_BROKER_LISTENER_NAME}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_CONTROLLER_LISTENER_NAMES=${KAFKA_CONTROLLER_LISTENER_NAMES}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}

      - CLUSTER_ID=${CLUSTER_ID}

      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=${KAFKA_TRANSACTION_STATE_LOG_MIN_ISR}
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=${KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR}
      - KAFKA_LOG_DIRS=${KAFKA_LOG_DIRS}
    healthcheck:
#      test: [ "CMD-SHELL", "kafka-broker-api-versions.sh --bootstrap-server kafka:9092 || exit 1" ]
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/9092' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  auth-service:
    image: ${DOCKERHUB_USERNAME}/task-planner:auth-service-${IMAGE_TAG}
    build: ./auth-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - task-planner-network
    env_file:
      - ./auth-service/.env

  mail-sender-service:
    image: ${DOCKERHUB_USERNAME}/task-planner:mail-sender-service-${IMAGE_TAG}
    build: ./mail-sender-service
    depends_on:
      kafka:
        condition: service_healthy
    #    ports:
    #      - "8083:8083"
    networks:
      - task-planner-network
    env_file:
      - ./mail-sender-service/.env

  planner-service:
    image: ${DOCKERHUB_USERNAME}/task-planner:planner-service-${IMAGE_TAG}
    build: ./planner-service
    depends_on:
      mail-sender-service:
        condition: service_completed_successfully
      auth-service:
        condition: service_completed_successfully
    #    ports:
    #      - "8082:8082"
    networks:
      - task-planner-network
    env_file:
      - ./planner-service/.env

networks:
  task-planner-network:
    driver: bridge

volumes:
  postgres-data:
  kafka-data: