spring:
  config:
    import: "optional:file:.env[.properties]"

  kafka:
    bootstrap-servers: ${KAFKA_ADDRESS}
    consumer:
      enable-auto-commit: false
    listener:
      ack-mode: record


  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

#server:
#  address: localhost
#  port: 8082
#

logging:
  structured:
    json:
      enabled: true
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} [traceId=%X{traceId:-}, uri=%X{uri:-}] - %msg%n"