CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE IF NOT EXISTS public.users
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email         VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(32)  NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_idx ON public.users (LOWER(email));

CREATE TABLE IF NOT EXISTS public.tasks
(
    id          BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id     BIGINT  REFERENCES public.users (id)       NOT NULL,
    title       VARCHAR(128)                               NOT NULL,
    description VARCHAR(1064)                                  NULL,
    time_added  TIMESTAMP                                  NOT NULL,
    status      boolean                                    NOT NULL,
    time_marked_true TIMESTAMP                                 NULL
);
CREATE INDEX IF NOT EXISTS tasks_user_id_idx ON public.tasks(user_id);
CREATE INDEX IF NOT EXISTS tasks_title_lower_case_idx ON public.tasks (LOWER(title));