CREATE USER "${POSTGRES_PLANNER_SERVICE_USER}" WITH PASSWORD '${POSTGRES_PLANNER_SERVICE_PASSWORD}';
GRANT CONNECT ON DATABASE auth TO "${POSTGRES_PLANNER_SERVICE_USER}";
GRANT USAGE ON SCHEMA auth.public TO "${POSTGRES_PLANNER_SERVICE_USER}";
GRANT SELECT ON ALL TABLES IN SCHEMA auth.public TO "${POSTGRES_PLANNER_SERVICE_USER}";
GRANT SELECT ON ALL SEQUENCES IN SCHEMA auth.public TO "${POSTGRES_PLANNER_SERVICE_USER}";

ALTER DEFAULT PRIVILEGES IN SCHEMA auth.public GRANT SELECT ON TABLES TO "${POSTGRES_PLANNER_SERVICE_USER}";
ALTER DEFAULT PRIVILEGES IN SCHEMA auth.public GRANT SELECT ON SEQUENCES TO "${POSTGRES_PLANNER_SERVICE_USER}";